import { describe, expect, it } from "vitest";

import * as buffers from "../packages/buffers/src/index.js";
import * as compiler from "../packages/compiler/src/index.js";
import * as runtime from "../packages/runtime/src/index.js";
import * as schema from "../packages/schema/src/index.js";

describe("public package runtime exports", () => {
  it("keeps the @exornea/zeno-buffers root export surface stable", () => {
    expect(Object.keys(buffers).sort()).toMatchInlineSnapshot(`
      [
        "createF32PackPlan",
        "createUintPackPlan",
        "histogramU16Field",
        "histogramU8Field",
        "packF32FieldsWhereU16Eq",
        "packF32FieldsWhereU8Eq",
        "packF32PlanWhereU16Eq",
        "packF32PlanWhereU8Eq",
        "packUintFields",
        "packUintFieldsWhereU16Eq",
        "packUintFieldsWhereU8Eq",
        "packUintPlan",
        "packUintPlanWhereU16Eq",
        "packUintPlanWhereU8Eq",
      ]
    `);
  });

  it("keeps the @exornea/zeno-runtime root export surface stable", () => {
    expect(Object.keys(runtime).sort()).toMatchInlineSnapshot(`
      [
        "BytesSpanView",
        "BytesVectorView",
        "DynamicLayoutArena",
        "DynamicLayoutWriter",
        "DynamicStructVectorView",
        "FixedArrayView",
        "FixedBytesArrayView",
        "FixedBytesVectorView",
        "FixedScalarArrayView",
        "FixedStringArrayView",
        "FixedStringVectorView",
        "FixedStructArrayView",
        "POINTER32_BYTE_LENGTH",
        "POINTER32_NULL",
        "PointerVectorView",
        "ProjectionView",
        "SCALAR_KINDS",
        "SPAN32_BYTE_LENGTH",
        "ScalarVectorView",
        "SharedDynamicLayoutWriter",
        "StructVectorView",
        "Utf8SpanView",
        "Utf8VectorView",
        "VECTOR32_BYTE_LENGTH",
        "VectorView",
        "ZENO_FRAME_HEADER_BYTE_LENGTH",
        "ZENO_FRAME_LAYOUT_HASH_NONE",
        "ZENO_FRAME_VERSION_MAJOR",
        "assertZenoFrameHeader",
        "assertZenoFramePayload",
        "bytesEqual",
        "checkedZenoFramePayloadView",
        "decodeFixedText",
        "decodeFixedUtf8",
        "decodeText",
        "encodeText",
        "endsWithAscii",
        "equalsAscii",
        "fixedBytesView",
        "hashBytes",
        "includesAscii",
        "initializeSharedArenaShard",
        "isSharedDescriptorPublished",
        "publishSharedDescriptor",
        "readScalar",
        "readSpan32Descriptor",
        "readVector32Descriptor",
        "readZenoFrameHeader",
        "resetSharedDescriptor",
        "scalarByteLength",
        "sharedArenaCursorCell",
        "sharedArenaShard",
        "sharedArenaView",
        "sharedDescriptorStateCell",
        "spanEndsWithAscii",
        "spanEqualsAscii",
        "spanHashBytes",
        "spanIncludesAscii",
        "spanStartsWithAscii",
        "startsWithAscii",
        "traversePointerChain",
        "writeFixedBytes",
        "writeFixedText",
        "writeFixedUtf8",
        "writeScalar",
        "writeSpan32Descriptor",
        "writeVector32Descriptor",
        "writeZenoFrameHeader",
        "zenoFramePayloadView",
      ]
    `);
  });

  it("keeps the @exornea/zeno-compiler root export surface stable", () => {
    expect(Object.keys(compiler).sort()).toMatchInlineSnapshot(`
      [
        "MEASUREMENT_LAYERS",
        "ambiguousLayout",
        "analyzeProjectionFile",
        "analyzeProjectionSourceFile",
        "andThen",
        "assertLayoutManifest",
        "createDiagnostic",
        "createIrDiagnostic",
        "createLayoutManifest",
        "diffLayoutManifests",
        "duplicateDefinition",
        "emitProjectionFile",
        "emitProjectionFileBarrel",
        "emitProjectionFileParts",
        "emitProjectionFileWithSourceMap",
        "emitStructView",
        "err",
        "formatDiagnosticLocation",
        "formatLayoutDiff",
        "formatLayoutInspection",
        "insufficientResolution",
        "isErr",
        "isLayoutManifest",
        "isOk",
        "layerCanObserve",
        "layoutInvariantViolation",
        "lowerField",
        "mapResult",
        "measure",
        "normalizeScanKernelMode",
        "ok",
        "parseScanKernelMode",
        "unsupportedAtPhase",
        "validateLayouts",
      ]
    `);
  });

  it("keeps the @exornea/zeno-schema runtime helper export surface stable", () => {
    expect(Object.keys(schema).sort()).toMatchInlineSnapshot(`
      [
        "POINTER32_BYTE_LENGTH",
        "POINTER32_NULL",
        "SCALAR_KINDS",
        "SPAN32_BYTE_LENGTH",
        "VECTOR32_BYTE_LENGTH",
        "alignTo",
        "scalarAlignment",
        "scalarByteLength",
        "scalarGetterMethod",
        "scalarSetterMethod",
        "scalarTsType",
      ]
    `);
  });
});
